#!/sbin/openrc-run
# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="DisplayLink Manager Service"

supervisor="supervise-daemon"
command="/usr/lib/displaylink/DisplayLinkManager"
directory="/usr/lib/displaylink"
respawn_delay=5

depend() {
	after display-manager
	need localmount
	use logger
}

start_pre() {
	modprobe evdi || return 1
}
